<?php
$columnsNotInYii = $model->getColumnsNotInYii();
if(isset($columnsNotInYii) && count($columnsNotInYii)>0){
?>
    <br><div style=text-align:center>These are columns that have been dynamically generated by the system</div><br>
<?php
    foreach($columnsNotInYii as $column){

        if(strpos($column->dbType, 'datetime') !== false){
            {
                echo $form->textFieldGroup($model, $column->name, array(
                    'labelOptions' => array('class' => 'col-sm-2 col-md-3'),
                    'wrapperHtmlOptions' => array('class' => 'col-sm-6 col-md-6 input-group-sm'),
                    'prepend' => '<i class="fa fa-gear"></i>',
                    'options' => array(
                        'format' => 'yyyy-mm-dd hh:ii:ss',
                    ),
                    'widgetOptions' => array('htmlOptions' => array('maxlength' => 45,)),
                ));
            }
        }
        elseif(strpos($column->dbType, 'date') !== false){
            echo $form->datePickerGroup(
                $model,
                $column->name,
                array(
                    'labelOptions' => array('class' => 'col-sm-2 col-md-3'),
                    'wrapperHtmlOptions' => array('class' => 'col-sm-6 col-md-6 input-group-sm'),
                    'widgetOptions' => array(
                        'options' => array(
                            'language' => 'en',
                            'format' => 'yyyy-mm-dd',
                        ),
                    ),
                    'prepend' => '<i class="fa fa-calendar"></i>',
                    'prependOptions' => array('inputGroupOptions' => array('class' => 'input-group-sm')),
                )
            );

        }else{
            echo $form->textFieldGroup($model, $column->name, array(
                'labelOptions' => array('class' => 'col-sm-2 col-md-3'),
                'wrapperHtmlOptions' => array('class' => 'col-sm-6 col-md-6 input-group-sm'),
                'prepend' => '<i class="fa fa-gear"></i>',
                'widgetOptions' => array('htmlOptions' => array('maxlength' => 45,)),
            ));
        }
    }
}